defaults:
  - liam_ego/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 3e6
LR: 3e-4
ENCODER_DECODER_LR: 7e-4
ENT_COEF: 0.001
CLIP_EPS: 0.1
ANNEAL_LR: false
UPDATE_EPOCHS: 5
ENCODER_HIDDEN_DIM: 128
ENCODER_OUTPUT_DIM: 20 # Embedding dimension
DECODER_HIDDEN_DIM: 128
POLICY_INPUT_DIM: 20 # Embedding dimension + observation dimension (obs dim added in the run script)