defaults:
  - lbrdiv/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 4.5e7
PARTNER_POP_SIZE: 3
NUM_ENVS: 64
LR: 5e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
CLIP_EPS: 0.05
ENT_COEF: 0.01
ego_train_algorithm: 
  TOTAL_TIMESTEPS: 3e7
  LR: 1e-4
  ENT_COEF: 0.01
  CLIP_EPS: 0.05